### PR TITLE
add Hallo

### PR DESCRIPTION
**Pull request by lenaSidan**
hello

### CODE REVIEW

**Review by Aliona46 — APPROVED** [review]

**Review by Tsarukyula — APPROVED** [review]
Super!

**Review by AndreiBakhtinov — APPROVED** [review]
Good job!

**Review by OuuAlex — APPROVED** [review]
God job!

**Review by nata-bo — APPROVED** [review]
super

**Review by KonstantinGlazunov — APPROVED** [review]

**Review by KonstantinGlazunov — APPROVED** [review]

**Review by rugbymann — APPROVED** [review]

**Review by viktoriaustymova — APPROVED** [review]

**Pull request merged**
